#
# Standard Makefile for a Webots physics shared library
#
# Author: Olivier.Michel@cyberbotics.com
# Date:   August 30th, 2006.
#
CPP_SOURCES=khr2_physics.cpp rcb3_physics.cpp

ifndef WEBOTS_HOME_PATH
WEBOTS_HOME_PATH=$(WEBOTS_HOME)
endif

include $(WEBOTS_HOME_PATH)/projects/default/plugins/physics/Makefile.include
